import { MenuItem } from '@app/models';

export const MENU: MenuItem[] = [
  {
    label: 'Tableau de bord',
    icon: 'dashboard',
    type: 'link',
    route: 'dashboard',
  },
  {
    label: 'Recherche Avancée',
    icon: 'search',
    type: 'link',
    route: 'appointments',
  },
  {
    label: 'Statistiques Avancées',
    icon: 'query_stats',
    type: 'link',
    route: 'stats',
    // roles: [4, 3, 2],
  },
  {
    label: 'Paiements en ligne',
    icon: 'credit_card',
    type: 'link',
    route: 'online-payments',
  },
  {
    label: 'Commercial',
    icon: 'people',
    type: 'sub',
    route: 'commercial',
    children: [
      {
        label: 'Gestion Clients',
        icon: 'edit_note',
        type: 'subchild',
        route: 'clients',
      },
      {
        label: 'Gestion Stock',
        icon: 'inventory_2',
        type: 'subchild',
        route: 'stock',
      },
      {
        label: 'Catégories',
        icon: 'category',
        type: 'subchild',
        route: 'commercial/categories',
      },
      {
        label: 'Code Promotion',
        icon: 'confirmation_number',
        type: 'subchild',
        route: 'commercial/code-promo',
      },
      {
        label: 'Promotions',
        icon: 'loyalty',
        type: 'subchild',
        route: 'commercial/promotions',
      },
    ],
  },
  {
    label: 'Paiements',
    icon: 'payments',
    type: 'link',
    route: 'paiements',
    roles: [4, 3, 2],
  },
  {
    label: 'Historique',
    icon: 'history',
    type: 'link',
    route: 'historique',
    roles: [4, 3, 2],
  },
  {
    label: 'Agendas',
    icon: 'event_note',
    type: 'link',
    route: 'agenda',
  },
  {
    label: 'Accès',
    icon: 'vpn_key',
    type: 'link',
    route: 'acces',
    roles: [4, 3],
  },
  {
    label: "Comité d'entreprise",
    icon: 'groups',
    type: 'link',
    route: 'partner',
  },
  {
    label: 'Mails et SMS',
    icon: 'mail',
    type: 'sub',
    children: [
      {
        label: 'Paramètres Mails',
        icon: 'settings',
        type: 'subchild',
        route: 'communication/mails/parametres',
        roles: [4, 3],
      },
      {
        label: 'Templates Mails',
        icon: 'article',
        type: 'subchild',
        route: 'communication/mails/templates',
        roles: [4, 3],
      },
      {
        label: 'Paramètres SMS',
        icon: 'settings',
        type: 'subchild',
        route: 'communication/sms/parametres',
        roles: [4, 3],
      },
      {
        label: 'Templates SMS',
        icon: 'sms',
        type: 'subchild',
        route: 'communication/sms/templates',
        roles: [4, 3],
      },
      {
        label: 'Statistiques SMS',
        icon: 'bar_chart',
        type: 'subchild',
        route: 'communication/sms/statistiques',
        roles: [4, 3],
      },
    ],
  },
  {
    label: 'Paramétrage',
    icon: 'settings',
    type: 'sub',
    route: 'settings',
    children: [
      {
        label: 'Gestion des utilisateurs',
        icon: 'Person',
        type: 'link',
        route: 'settings/users',
      },
      {
        label: 'Agenda contrôleur',
        icon: 'supervisor_account',
        type: 'link',
        route: 'settings/controllers',
      },
      {
        label: 'Congés et jours Fériés',
        icon: 'calendar_month',
        type: 'link',
        route: 'settings/holiday',
      },
      {
        label: 'Champs supplémentaires',
        icon: 'settings',
        type: 'subchild',
        route: 'settings/fields',
      },
      {
        label: 'Liste noire',
        icon: 'do_not_touch',
        type: 'subchild',
        route: 'settings/black-list',
      },
      {
        label: 'Configuration agenda',
        icon: 'settings',
        type: 'subchild',
        route: 'settings/configuration-agenda',
      },
    ],
  },
  {
    label: 'Modules',
    icon: 'extension',
    type: 'link',
    route: 'modules',
    roles: [4, 3],
  },
  {
    label: 'External Link 1',
    icon: 'credit_card',
    type: 'extLink',
    externalUrl: 'https://www.youtube.com',
  },
  {
    label: 'External Link 2',
    icon: 'local_offer',
    type: 'extLink',
    externalUrl: 'https://www.google.com',
  },
  {
    label: 'Mes préférences',
    icon: 'person_outline',
    type: 'footer',
    route: 'preferences',
  },
  {
    label: 'Aide',
    icon: 'help_outline',
    type: 'footer',
    route: 'aide',
  },
  {
    label: 'À propos',
    icon: 'info',
    type: 'footer',
    route: 'a-propos',
  },
];
